# Generated by Django 4.1.7 on 2023-03-11 06:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContentViews',
            new_name='ContentView',
        ),
        migrations.RenameField(
            model_name='certificate',
            old_name='cource',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='cource',
            new_name='course',
        ),
    ]
