# Generated by Django 4.1.7 on 2023-03-15 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(null=True, upload_to='category/icons/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='content',
            name='video',
            field=models.FileField(upload_to='course/lesson/content/%Y/%m/%d/', verbose_name='Video'),
        ),
    ]
