# Generated by Django 4.1.7 on 2023-03-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_course_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='text_for_certificate',
            field=models.TextField(blank=True, null=True),
        ),
    ]
