JAZZMIN_SETTINGS = {
    "site_title": "Ayol Uchun",
    "site_header": "Ayol Uchun",
    "site_brand": "Ayol Uchun",
    "site_logo": None,
    "login_logo": None,
    "login_logo_dark": None,
    "site_logo_classes": "img-circle",
    "site_icon": None,
    "welcome_sign": "Welcome to the Ayol Uchun admin",
    "copyright": "Ayol Uchun Ltd",
    "search_model": "account.User",
    "user_avatar": None,
    "topmenu_links": [
        {"name": "Home", "url": "admin:index", "permissions": ("auth.view_user",)},
        {"name": "Support", "url": "https://github.com/farridav/django-jazzmin/issues", "new_window": True},
        {"model": "Ayol Uchun.User"},
        {"app": "account"}
    ],
    "usermenu_links": [
        {"name": "Support", "url": "https://github.com/farridav/django-jazzmin/issues", "new_window": True},
        {"model": "auth.user"}
    ],
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "order_with_respect_to": ("auth", "users", "books.author", "books.book"),
    "icons": {
        "auth": "fas fa-users-cog",
        "users.user": "fas fa-user",
        "auth.Group": "fas fa-sharp fa-regular fa-user-shield",
        "users.Blog": "fas fa-newspaper",
        "users.Lead": "fas fa-light fa-user-nurse",
        "users.LeadIncrement": "fas fa-light fa-user-check",
        "groups.Branch": "fa regular fa-code-branch",
        "groups.Company": "fa regular fa-building",
        "groups.Course": "fa solid fa-layer-group",
        "groups.Group": "fa solid fa-layer-group",
        "groups.Room": "fa solid fa-door-open",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    "related_modal_active": False,
    "custom_css": None,
    "custom_js": None,
    "use_google_fonts_cdn": True,
    "show_ui_builder": False,
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {"users.user": "collapsible", "auth.group": "vertical_tabs"},
    "language_chooser": False,
}
