# Generated by Django 4.1.7 on 2023-03-13 07:23

from django.db import migrations
import thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='get_thumbnails',
            field=thumbnails.fields.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=thumbnails.fields.ImageField(null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Photo'),
        ),
    ]
