# Generated by Django 4.1.7 on 2023-03-15 07:17

from django.db import migrations
import thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=thumbnails.fields.ImageField(default='user.png', null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Photo'),
        ),
    ]
